<<<<<<< HEAD
site_name: Battle Jack - 
site_description: To add

theme:
  name: material
  palette: 
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
=======
site_name: My Docs

theme:
  name: material
  language: it

plugins:
  - search
  - autorefs

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


extra:
  alternate:
    - name: English
      link: /en/
      lang: en
>>>>>>> a78d1e1 (nuovo)
