site_name: BattleJack
site_url: https://cronosvirus00.github.io/BattleJack/
repo_url: https://github.com/CronosVirus00/BattleJack

validation:
  links:
    absolute_links: relative_to_docs


theme:
  name: material
  language: it
  features:
    - navigation.tabs          # Schede in alto[cite: 1]
    - navigation.tabs.only     # Nasconde la navigazione ad albero a sinistra[cite: 1]
    - navigation.top           # Pulsante torna su[cite: 1]
    - search.suggest           #[cite: 1]
    - search.highlight         #[cite: 1]
    - toc.integrate            # Porta l'indice (TOC) nel pannello di sinistra

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - autorefs
  - glightbox

markdown_extensions:
  - def_list
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true