site_name: BattleJack
site_url: https://cronosvirus00.github.io/BattleJack/
repo_url: https://github.com/CronosVirus00/BattleJack

validation:
  links:
    absolute_links: relative_to_docs

theme:
  name: material
  language: it
  features:
    - navigation.tabs          # Top menu bar tabs
    - navigation.tabs.only          # remove side bar
    - navigation.sections      # Group sidebar links cleanly into collapsible sections
    - navigation.expand        # Keep sidebar sections expanded by default
    - navigation.top           # Back-to-top button on scroll
    - search.suggest           # Interactive search suggestions
    - search.highlight         # Highlight searched keywords on pages

plugins:
  - search
  - autorefs
  - glightbox

markdown_extensions:
  - def_list
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true